package haveno.cli;

/**
 * Currently supported API methods.
 */
public enum Method {
    canceloffer,
    closetrade,
    confirmpaymentreceived,
    confirmpaymentsent,
    createoffer,
    editoffer,
    createpaymentacct,
    createcryptopaymentacct,
    getaddressbalance,
    getbalance,
    getxmrprice,
    getfundingaddresses,
    @Deprecated // Since 27-Dec-2021.
    getmyoffer, // Endpoint to be removed from future version. Use getoffer instead.
    getmyoffers,
    getoffer,
    getoffers,
    getpaymentacctform,
    getpaymentaccts,
    getpaymentmethods,
    gettrade,
    gettrades,
    failtrade,
    unfailtrade,
    gettransaction,
    getunusedxmraddress,
    getversion,
    lockwallet,
    registerdisputeagent,
    removewalletpassword,
    setwalletpassword,
    takeoffer,
    unlockwallet,
    withdrawfunds,
    stop,
    getxmrseed,
    getxmrprimaryaddress,
    getxmrnewsubaddress,
    getxmrtxs,
    createxmrtx,
    relayxmrtxs,
    getchatmessages,
    sendchatmessage,
    getpaymentaccountform,
    deletepaymentaccount,
    validateformfield,
    completetrade,
    sendxmr,
    // Account management methods
    accountexists,
    isaccountopen,
    createaccount,
    openaccount,
    isappinitialized,
    changepassword,
    closeaccount,
    deleteaccount,
    backupaccount,
    restoreaccount,
    // Dispute methods
    getdispute,
    getdisputes,
    opendispute,
    resolvedispute,
    senddisputechatmessage,
    // XMR connection methods
    addconnection,
    removeconnection,
    getconnection,
    getconnections,
    setconnection,
    checkconnection,
    checkconnections,
    startcheckingconnection,
    stopcheckingconnection,
    getbestconnection,
    setautoswitch,
    getautoswitch,
    // XMR node methods
    isxmrnodeonline,
    getxmrnodesettings,
    startxmrnode,
    stopxmrnode
}
